travis:
  secure:
    BINSTAR_TOKEN: lnCWZBfFFIqsw8xr3054C5+T7g24X/6U6fSxLZuqSLUK+TDPrk2E9fTSjdFT2V9KJaz77ulJGZKhHrKQpqwJX+XlRxbCne8vEhdnyKu1PzejSdGvKak+0qy/Z2BDoT7VMVBziAiYP8My4U18sP8vgj8GbXpBF4M8MRmRKOEvDqKZJokSk70dpdjYreDeNitknu/XWu+aKBUhe1GRQx8eRI5LkJoiNkytdflQy9d4+SWLspnNnvbuwWe7/RHgEA1HDMK/S4mcs+uRhO8X3n47nkoE3Qf6rleTdNsHO647/9bWuiNmAzvBIw1sXBNqVqhdEEdFiFSFsi+y0OqVKBvW+Z5pjTPaShKPCPnt3BVpmWa7koGEtwf45CCF8oo3xwiXg7tY6BS4YJG1TBCYNqYaG6Px/X+Tb5qiiZctaDOj64KYt/bF2wtxrk0NK/jeBlJ2MPN9oP8HctwJqAlcftKpi9khX8Sp4RRhVnqitUJ8HMGIt0hvdhePFozJAm4sifIJQfXsqrpw4+NcL0EyOtOUAv5N1y8J8SQIQJTgpnIeJ59YOyiR7RSv9vsImx6vecyk3eWo5A/OaDD4sMUy+tZCyU+aZAGG6ouqfSkOcSGRXlhdN83MENdb0wL41EsiQDEObKPnNINbI+44eReUTqT1C3blHcAJUoW3YK6up1OqTfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
